spring.application.name=SpringVisitMinIO

#MinIO相关配置
minio.endpoint=http://localhost:9000
minio.user=root
minio.password=15275069098pang
minio.bucketName=myfiles

#处理大文件上传问题
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=5000MB

# 禁用Tomcat最大POST大小限制
server.tomcat.max-swallow-size=-1
server.tomcat.max-post-size=-1
